name: Web E2E tests

on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      
      # clone do projeto pra uma machine
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      - name: Instalando dependencias
        run: npm install

      # and run all Cypress tests
      - name: Cypress run
        #uses: cypress-io/github-action@v6
        run: npm run test-trabalho-final
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorios
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos